### ISSUE TITLE
State are not restored after rebind

### ISSUE THREAD

**Issue by OlafStaf** [processone/smack-rebind#1]
When we successfully rebind to previous session the state of `xmppconnection` are not restored. Because `bindResourceAndEstablishSession` is never called. And thats why all necessary info is null (user inside AbstractXMPPConnection.class etc.)

**Comment by ajayld** [comment]
Any update on this issue?

**Comment by prefiks** [comment]
Hello,

Sorry i completely forgot about this, i will try to fix that in coming days.

**Comment by yudhisthira123** [comment]
@prefiks Can you please provide tentative time line?

**Comment by prefiks** [comment]
Hopefully this week, or early next one.

**Comment by prefiks** [comment]
Should be fixed by 06cdf74b4f7a8207b7c84802319b7986bb22f311
